baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
publishDir = "docs"
contentDir   = "content"
googleAnalytics = "UA-19819210-1"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Turgay Özgür personal web site and blog."
  keywords = "homepage, blog, science, informatics, development, programming, turgayozgur"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:ozgurtrgy@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/turgayozgur"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/turgayozgur"

  [[params.social]]
    name = "medium"
    url  = "https://turgayozgur.medium.com"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/turgayozgur"

[languages]
  [languages.en]
    title = "Turgay Özgür"
    subtitle = ""
    homeSubtitle = "Software Consultant"
    keywords = ""
    copyright = "© 2024 turgayozgur.com"
    readOtherPosts = "Read other posts"

    [languages.en.params.footer]
      copyright = false
      bottomText = ['<!-- TradingView Widget BEGIN --><div class="tradingview-widget-container">  <div class="tradingview-widget-container__widget"></div>  <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span>Track all markets on TradingView</span></a></div>  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-single-quote.js" async>  {  "symbol": "FX:EURUSD",  "width": "100%",  "isTransparent": true,  "colorTheme": "dark",  "locale": "en"}  </script></div><!-- TradingView Widget END -->']

    [languages.en.params.logo]
      logoText = "turgayozgur:"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Blog"
        url = "/posts"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"

# And you can even create generic menu
# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "/about"
#   [[menu.main]]
#     identifier = "blog"
#     name       = "Blog"
#     url        = "/posts"